# Generated by Django 2.0.5 on 2018-11-26 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDcard',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('nation', models.CharField(max_length=10)),
                ('brith', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('ID', models.CharField(max_length=18, primary_key=True, serialize=False)),
            ],
        ),
    ]
